ARDUINOS:
  MEGA:
    active: true
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: MEGA
  UNO:
    active: false
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: UNO
FIREGROUPS: !!python/object/apply:collections.OrderedDict
- - - F
    - channel: '1'
      name: F
      sub_groups: !!python/object/apply:collections.OrderedDict
      - - [E, '2']
  - - D
    - channel: '3'
      name: D
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
  - - C
    - channel: '4'
      name: C
      sub_groups: !!python/object/apply:collections.OrderedDict
      - - [B, '5']
        - [A, '6']
password: $5$rounds=535000$Uq75eElEg79tZfqq$e/8G1ZEuVZJYWv2Hngoby7Bg4afCqskr.QYPfXQeRS.
text: Now is the time for all good men to come to the aid of the party
