ARDUINOS:
  MEGA:
    active: false
    channels: [1, 2, 3]
    name: MEGA
  UNO:
    active: true
    channels: [1, 2, 3]
    name: UNO
password: $5$rounds=535000$Uq75eElEg79tZfqq$e/8G1ZEuVZJYWv2Hngoby7Bg4afCqskr.QYPfXQeRS.
text: !!python/unicode 'Now is the time for all good men to come to the aid of the
  party'

FIREGROUPS:
  First:
    name : First
    channel: 1
    sub_groups: {sub_1 : 2}
