ARDUINOS:
  MEGA: {active: true, channels: [1, 2, 3], name: MEGA}
  UNO: {active: false, channels: [4, 5, 6], name: UNO}
password: $5$rounds=535000$Uq75eElEg79tZfqq$e/8G1ZEuVZJYWv2Hngoby7Bg4afCqskr.QYPfXQeRS.
text: !!python/unicode 'Now is the time for all good men to come to the aid of the
  party'
