ARDUINOS:
  MEGA:
    active: true
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: MEGA
  UNO:
    active: false
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: UNO
FIREGROUPS: !!python/object/apply:collections.OrderedDict
- - - Test_3
    - blurb: ''
      channel: '1'
      name: Test
      sub_groups: !!python/object/apply:collections.OrderedDict
      - - - !!python/tuple ['SubA ', 1]
          - '2'
        - - !!python/tuple [subB, 2]
          - '3'
  - - TestC_4
    - blurb: ''
      channel: '4'
      name: TestC
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
  - - TestD_5
    - blurb: ''
      channel: '5'
      name: TestD
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
  - - TestE_6
    - blurb: ''
      channel: '6'
      name: TestE
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
password: $5$rounds=535000$Uq75eElEg79tZfqq$e/8G1ZEuVZJYWv2Hngoby7Bg4afCqskr.QYPfXQeRS.
text: Now is the time for all good men to come to the aid of the party.
