ARDUINOS:
  MEGA:
    active: true
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: MEGA
  UNO:
    active: false
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: UNO
FIREGROUPS:
  Test_1:
    channel: '1'
    name: Test_1
    sub_groups: {}
  Test_2:
    channel: '2'
    name: Test_2
    sub_groups: {}
password: $5$rounds=535000$Uq75eElEg79tZfqq$e/8G1ZEuVZJYWv2Hngoby7Bg4afCqskr.QYPfXQeRS.
text: Now is the time for all good men to come to the aid of the party
