ARDUINOS:
  MEGA:
    active: true
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: MEGA
  UNO:
    active: false
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: UNO
FIREGROUPS: !!python/object/apply:collections.OrderedDict
- - - Test_1
    - blurb: ''
      channel: ''
      name: Test
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
  - - _2
    - blurb: ''
      channel: ''
      name: ''
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
  - - _3
    - blurb: ''
      channel: ''
      name: ''
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
  - - _4
    - blurb: ''
      channel: ''
      name: ''
      sub_groups: !!python/object/apply:collections.OrderedDict
      - []
password: $5$rounds=535000$Uq75eElEg79tZfqq$e/8G1ZEuVZJYWv2Hngoby7Bg4afCqskr.QYPfXQeRS.
text: Now is the time for all good men to come to the aid of the party.
